version: "2"  
  
linters:  
  default: standard  
  enable:  
    - gosec         # Security checks  
    - bodyclose     # HTTP body close checks  
    - revive        # Configurable linter  
  
formatters:  
  enable:  
    - gofmt         # Format checking  
    - goimports     # Import ordering  
  
run:  
  timeout: 5m  
  modules-download-mode: readonly  
  tests: true  
  
issues:  
  max-issues-per-linter: 50  
  max-same-issues: 3  
  
output:  
  formats:  
    text:  
      path: stdout  
      print-issued-lines: true  
      print-linter-name: true
