// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type Event interface {
	IsEvent()
	GetID() string
	GetBlockNumber() string
	GetTxHash() string
	GetTxIndex() int
	GetLogIndex() int
	GetTimestamp() time.Time
	GetContract() string
	GetEventName() string
}

type Block struct {
	Number     string    `json:"number"`
	Hash       string    `json:"hash"`
	Timestamp  time.Time `json:"timestamp"`
	ParentHash string    `json:"parentHash"`
}

type EventConnection struct {
	Edges      []*EventEdge `json:"edges"`
	PageInfo   *PageInfo    `json:"pageInfo"`
	TotalCount int          `json:"totalCount"`
}

type EventEdge struct {
	Cursor string        `json:"cursor"`
	Node   *GenericEvent `json:"node"`
}

type EventFilter struct {
	Contract  *string    `json:"contract,omitempty"`
	EventName *string    `json:"eventName,omitempty"`
	FromBlock *string    `json:"fromBlock,omitempty"`
	ToBlock   *string    `json:"toBlock,omitempty"`
	FromTime  *time.Time `json:"fromTime,omitempty"`
	ToTime    *time.Time `json:"toTime,omitempty"`
}

type EventOrder struct {
	Field     EventOrderField `json:"field"`
	Direction OrderDirection  `json:"direction"`
}

type GenericEvent struct {
	ID          string         `json:"id"`
	BlockNumber string         `json:"blockNumber"`
	TxHash      string         `json:"txHash"`
	TxIndex     int            `json:"txIndex"`
	LogIndex    int            `json:"logIndex"`
	Timestamp   time.Time      `json:"timestamp"`
	Contract    string         `json:"contract"`
	EventName   string         `json:"eventName"`
	Data        map[string]any `json:"data"`
}

func (GenericEvent) IsEvent()                     {}
func (this GenericEvent) GetID() string           { return this.ID }
func (this GenericEvent) GetBlockNumber() string  { return this.BlockNumber }
func (this GenericEvent) GetTxHash() string       { return this.TxHash }
func (this GenericEvent) GetTxIndex() int         { return this.TxIndex }
func (this GenericEvent) GetLogIndex() int        { return this.LogIndex }
func (this GenericEvent) GetTimestamp() time.Time { return this.Timestamp }
func (this GenericEvent) GetContract() string     { return this.Contract }
func (this GenericEvent) GetEventName() string    { return this.EventName }

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type Query struct {
}

type Subscription struct {
}

type SyncStatus struct {
	Network      string     `json:"network"`
	ChainID      string     `json:"chainID"`
	CurrentBlock string     `json:"currentBlock"`
	HeadBlock    string     `json:"headBlock"`
	Lag          string     `json:"lag"`
	IsSynced     bool       `json:"isSynced"`
	LastSyncTime *time.Time `json:"lastSyncTime,omitempty"`
}

type EventOrderField string

const (
	EventOrderFieldBlockNumber EventOrderField = "BLOCK_NUMBER"
	EventOrderFieldTimestamp   EventOrderField = "TIMESTAMP"
)

var AllEventOrderField = []EventOrderField{
	EventOrderFieldBlockNumber,
	EventOrderFieldTimestamp,
}

func (e EventOrderField) IsValid() bool {
	switch e {
	case EventOrderFieldBlockNumber, EventOrderFieldTimestamp:
		return true
	}
	return false
}

func (e EventOrderField) String() string {
	return string(e)
}

func (e *EventOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EventOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EventOrderField", str)
	}
	return nil
}

func (e EventOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *EventOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e EventOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type OrderDirection string

const (
	OrderDirectionAsc  OrderDirection = "ASC"
	OrderDirectionDesc OrderDirection = "DESC"
)

var AllOrderDirection = []OrderDirection{
	OrderDirectionAsc,
	OrderDirectionDesc,
}

func (e OrderDirection) IsValid() bool {
	switch e {
	case OrderDirectionAsc, OrderDirectionDesc:
		return true
	}
	return false
}

func (e OrderDirection) String() string {
	return string(e)
}

func (e *OrderDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrderDirection", str)
	}
	return nil
}

func (e OrderDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrderDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrderDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
